Try test12 in MacOS gcc-10
Let's see if this one breaks in MacOS/Ubuntu, or none.

The other broken test, 25, gets me an interesting error message: 'File name too long'. In more detail:

OSError: Unable to create file (unable to open file: name = 'test_data/power_spectra_z18.00_FAST_FCOLL_TABLES=True_INHOMO_RECO=True_NUM_FILTER_STEPS_FOR_Ts=8_N_THREADS=4_USE_FFTW_WISDOM=True_USE_INTERPOLATION_TABLES=True_USE_MASS_DEPENDENT_ZETA=True_USE_MINI_HALOS=True_USE_RELATIVE_VELOCITIES=True_USE_TS_FLUCT=True_z_heat_max=25_zprime_step_factor=1.2.h5', errno = 63, error message = 'File name too long', flags = 13, o_flags = 602)